version: "3"
services:
  sonarqube:
    # Keep in mind that you need to install sonar-scanner manually!
    # Brew install sonar-scanner
    image: sonarqube:latest
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
    # JDBC: Java Database Connector
    # Default port for postgres is 5432 .
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
    ports:
    # Outside port is the left one.
      - "9000:9000"
  db:  # Authentication, logs and any other artefacts are stored in here.
    image: postgres:latest
    hostname: postgresql
    container_name: sonarqube_db
    environment:
      # If you change these credentials you need to change them for sonar service too.
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      # Database name which is needed for sonar service.
      POSTGRES_DB: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
